import type { Movie, Series, Channel, WatchingItem, KidsItem, User } from './types'

/** Pre-compute gradient strings at module-load time so JSX never runs template literals on each render */
function g(from: string, to: string): string {
  return `linear-gradient(160deg, ${from} 0%, ${to} 100%)`
}

export const MOVIES: Movie[] = [
  {
    id: 'm1',
    title: 'Rumo ao Infinito',
    year: 2024,
    duration: '2h 08min',
    genre: 'Ficção científica',
    rating: 12,
    quality: 'HD',
    description:
      'Em uma missão além dos limites do sistema solar, um astronauta enfrenta o desconhecido e descobre que o maior mistério pode estar mais perto do que imaginava.',
    cast: [
      { name: 'Lucas Andrade', role: 'Comandante Eva' },
      { name: 'Mariana Costa', role: 'Dra. Helena Ruiz' },
      { name: 'Pedro Soares', role: 'IA – Atlas' },
      { name: 'Carla Mendes', role: 'Capitã Yara' },
    ],
    director: 'Rafael Menezes',
    colorFrom: '#0c1a4a',
    colorTo: '#1a3a6b',
    type: 'movie',
  },
  {
    id: 'm2',
    title: 'Código Alvorada',
    year: 2024,
    duration: '1h 52min',
    genre: 'Ação',
    rating: 14,
    quality: 'HD',
    description: 'Um agente secreto descobre uma conspiração que ameaça a ordem global e precisa agir antes do amanhecer.',
    cast: [
      { name: 'Bruno Tavares', role: 'Agente Cross' },
      { name: 'Fernanda Lima', role: 'Dra. Nara' },
    ],
    director: 'Carlos Drummond',
    colorFrom: '#2a1a08',
    colorTo: '#4a2e10',
    type: 'movie',
  },
  {
    id: 'm3',
    title: 'Sobre as Ondas',
    year: 2023,
    duration: '1h 38min',
    genre: 'Drama',
    rating: 10,
    quality: 'HD',
    description: 'A jornada de uma surfista que busca o sonho olímpico enquanto enfrenta as perdas da vida.',
    cast: [
      { name: 'Ana Beatriz', role: 'Maya' },
      { name: 'João Victor', role: 'Treinador Kael' },
    ],
    director: 'Silvia Porto',
    colorFrom: '#051a2a',
    colorTo: '#0d3a5a',
    type: 'movie',
  },
  {
    id: 'm4',
    title: 'Guardiões do Último Portal',
    year: 2024,
    duration: '2h 15min',
    genre: 'Fantasia',
    rating: 12,
    quality: 'HD',
    description: 'Quatro guerreiros precisam impedir a abertura de um portal dimensional que liberaria seres do além.',
    cast: [
      { name: 'Marcos Vinicius', role: 'Talon' },
      { name: 'Priya Santos', role: 'Seer' },
    ],
    director: 'Renata Figueiredo',
    colorFrom: '#1a0a2a',
    colorTo: '#2e1050',
    type: 'movie',
  },
  {
    id: 'm5',
    title: 'Risos de Aluguel',
    year: 2024,
    duration: '1h 45min',
    genre: 'Comédia',
    rating: 10,
    quality: 'HD',
    description: 'Um comediante falido aceita um trabalho inusitado: ser pago para rir nas piadas de um magnata.',
    cast: [
      { name: 'Felipe Araújo', role: 'Dante' },
      { name: 'Luisa Mello', role: 'Carla' },
    ],
    director: 'Thiago Pires',
    colorFrom: '#2a1f00',
    colorTo: '#4a3800',
    type: 'movie',
  },
  {
    id: 'm6',
    title: 'Sombra no Espelho',
    year: 2023,
    duration: '1h 58min',
    genre: 'Terror',
    rating: 16,
    quality: 'HD',
    description: 'Uma psicóloga começa a questionar a realidade quando seu reflexo age de forma independente.',
    cast: [
      { name: 'Camila Ferreira', role: 'Dra. Lia' },
      { name: 'Rodrigo Maia', role: 'Inspetor Neves' },
    ],
    director: 'Helena Cruz',
    colorFrom: '#100820',
    colorTo: '#1e0f38',
    type: 'movie',
  },
  {
    id: 'm7',
    title: 'Velocidade Absoluta',
    year: 2024,
    duration: '2h 02min',
    genre: 'Ação',
    rating: 14,
    quality: '4K',
    description: 'Um piloto rebelde entra no torneio de corridas mais perigoso do mundo para salvar seu irmão.',
    cast: [
      { name: 'Diego Santos', role: 'Rex' },
      { name: 'Marina Luz', role: 'Juno' },
    ],
    director: 'Paulo Andrade',
    colorFrom: '#2a0808',
    colorTo: '#500e0e',
    type: 'movie',
  },
  {
    id: 'm8',
    title: 'O Pacto do Silêncio',
    year: 2023,
    duration: '1h 55min',
    genre: 'Suspense',
    rating: 16,
    quality: 'HD',
    description: 'Dois amigos de infância se reencontram e percebem que guardam um segredo que pode destruir tudo.',
    cast: [
      { name: 'Victor Hugo', role: 'Aldo' },
      { name: 'Tatiane Ramos', role: 'Vera' },
    ],
    director: 'Marcos Lima',
    colorFrom: '#080e1a',
    colorTo: '#101a30',
    type: 'movie',
  },
  {
    id: 'm9',
    title: 'Entre Estrelas',
    year: 2024,
    duration: '2h 10min',
    genre: 'Ficção científica',
    rating: 12,
    quality: 'HD',
    description: 'Dois astronautas ficam presos numa estação espacial e descobrem que precisam um do outro para sobreviver.',
    cast: [
      { name: 'Ana Luísa', role: 'Comandante Sol' },
      { name: 'Rafael Torres', role: 'Eng. Kai' },
    ],
    director: 'Julia Barros',
    colorFrom: '#0a0e28',
    colorTo: '#141e4a',
    type: 'movie',
  },
  {
    id: 'm10',
    title: 'Amor em Compasso',
    year: 2024,
    duration: '1h 42min',
    genre: 'Romance',
    rating: 10,
    quality: 'HD',
    description: 'Uma violoncelista e um maestro controverso têm suas vidas transformadas por uma parceria musical inesperada.',
    cast: [
      { name: 'Sofia Alves', role: 'Lena' },
      { name: 'Henrique Dias', role: 'Maestro Kurt' },
    ],
    director: 'Bianca Rocha',
    colorFrom: '#1a0a20',
    colorTo: '#300a38',
    type: 'movie',
  },
  {
    id: 'm11',
    title: 'A Maldição de Ravenhall',
    year: 2023,
    duration: '2h 05min',
    genre: 'Terror',
    rating: 16,
    quality: 'HD',
    description: 'Uma família se muda para uma mansão vitoriana e descobre que seus habitantes anteriores nunca foram embora.',
    cast: [
      { name: 'Patrícia Nogueira', role: 'Claire' },
      { name: 'Alexandre Costa', role: 'Thomas' },
    ],
    director: 'Fernando Braga',
    colorFrom: '#0e1408',
    colorTo: '#1c2810',
    type: 'movie',
  },
  {
    id: 'm12',
    title: 'O Grande Ilusionista',
    year: 2024,
    duration: '1h 48min',
    genre: 'Drama',
    rating: 12,
    quality: 'HD',
    description: 'Um ilusionista em decadência aceita sua última apresentação e decide fazer um truque que desafia a morte.',
    cast: [
      { name: 'Cláudio Mendes', role: 'Zeno' },
      { name: 'Rebeca Santos', role: 'Anya' },
    ],
    director: 'Isabela Freitas',
    colorFrom: '#18100a',
    colorTo: '#301e12',
    type: 'movie',
  },
  {
    id: 'm13',
    title: 'Missão Titã',
    year: 2024,
    duration: '2h 18min',
    genre: 'Ficção científica',
    rating: 12,
    quality: '4K',
    description: 'Uma equipe de élite é enviada à lua de Saturno para investigar sinais de vida inteligente.',
    cast: [
      { name: 'Gustavo Nery', role: 'Major Dax' },
      { name: 'Larissa Mota', role: 'Cientista Rook' },
    ],
    director: 'André Vilaça',
    colorFrom: '#080c20',
    colorTo: '#10183a',
    type: 'movie',
  },
  {
    id: 'm14',
    title: 'Doce Recomeço',
    year: 2023,
    duration: '1h 36min',
    genre: 'Comédia',
    rating: 10,
    quality: 'HD',
    description: 'Após uma separação, uma confeiteira decide abrir seu próprio negócio e reencontrar a felicidade.',
    cast: [
      { name: 'Juliana Faria', role: 'Bea' },
      { name: 'Leonardo Pires', role: 'Pierre' },
    ],
    director: 'Natalia Souza',
    colorFrom: '#1a0a14',
    colorTo: '#321020',
    type: 'movie',
  },
  {
    id: 'm15',
    title: 'Eco do Amanhã',
    year: 2024,
    duration: '1h 50min',
    genre: 'Drama',
    rating: 12,
    quality: 'HD',
    description: 'Em um futuro próximo, um cientista descobre que pode enviar mensagens para o passado, mas toda mudança tem um preço.',
    cast: [
      { name: 'Marcelo Fonseca', role: 'Dr. Leo' },
      { name: 'Alice Menezes', role: 'Sara' },
    ],
    director: 'Roberto Campos',
    colorFrom: '#0a1808',
    colorTo: '#142e10',
    type: 'movie',
  },
  {
    id: 'm16',
    title: 'Esquadrão Falcão',
    year: 2024,
    duration: '2h 00min',
    genre: 'Ação',
    rating: 14,
    quality: '4K',
    description: 'Uma unidade de elite militar é chamada para uma missão de resgate num território hostil sem saída.',
    cast: [
      { name: 'Rodrigo Falcão', role: 'Capitão Storm' },
      { name: 'Ana Karolina', role: 'Tenente Vox' },
    ],
    director: 'Sandro Leal',
    colorFrom: '#1e1008',
    colorTo: '#3a1c0a',
    type: 'movie',
  },
  {
    id: 'm17',
    title: 'A Bailarina',
    year: 2023,
    duration: '1h 55min',
    genre: 'Drama',
    rating: 10,
    quality: 'HD',
    description: 'Uma dançarina talentosa luta para se manter relevante em um mundo que está esquecendo suas raízes.',
    cast: [
      { name: 'Vitória Ramos', role: 'Nina' },
      { name: 'Caio Mendes', role: 'Coreógrafo Pavel' },
    ],
    director: 'Elisa Brandão',
    colorFrom: '#180820',
    colorTo: '#2c103c',
    type: 'movie',
  },
  {
    id: 'm18',
    title: 'Viagem de Volta',
    year: 2024,
    duration: '1h 44min',
    genre: 'Ação',
    rating: 14,
    quality: 'HD',
    description: 'Depois de 20 anos longe, um ex-piloto precisa cruzar o país para chegar ao filho que nunca conheceu.',
    cast: [
      { name: 'Marco Aurélio', role: 'Dante Cruz' },
      { name: 'Bia Costa', role: 'Rita' },
    ],
    director: 'Fabio Nunes',
    colorFrom: '#0a1030',
    colorTo: '#12204e',
    type: 'movie',
  },
]

export const SERIES: Series[] = [
  {
    id: 's1',
    title: 'Eclipse: A Nova Ordem',
    year: 2024,
    seasons: 1,
    genre: 'Ficção científica',
    rating: 14,
    quality: 'HD',
    description: 'Após um eclipse permanente, o mundo se reorganiza em torno de quem controla a última fonte de luz.',
    cast: [
      { name: 'Tiago Melo', role: 'Rael' },
      { name: 'Camila Nobre', role: 'Veda' },
    ],
    creator: 'Henrique Luz',
    colorFrom: '#08101a',
    colorTo: '#102030',
    type: 'series',
  },
  {
    id: 's2',
    title: 'Herdeiros do Império',
    year: 2023,
    seasons: 2,
    genre: 'Drama',
    rating: 16,
    quality: 'HD',
    description: 'Uma família poderosa mergulha em traição e ambição após a morte repentina do patriarca.',
    cast: [
      { name: 'Eduardo Pires', role: 'Lorenzo' },
      { name: 'Stella Cruz', role: 'Isolde' },
    ],
    creator: 'Monica Barros',
    colorFrom: '#180e08',
    colorTo: '#2c1a0e',
    type: 'series',
  },
  {
    id: 's3',
    title: 'Entre Mentiras',
    year: 2024,
    seasons: 1,
    genre: 'Suspense',
    rating: 16,
    quality: 'HD',
    description: 'Um jornalista investiga desaparecimentos numa pequena cidade e descobre que ninguém diz a verdade.',
    cast: [
      { name: 'Paulo Ramos', role: 'Félix' },
      { name: 'Nina Faria', role: 'Detetive Sol' },
    ],
    creator: 'Gustavo Vargas',
    colorFrom: '#081018',
    colorTo: '#0e1e2c',
    type: 'series',
  },
  {
    id: 's4',
    title: 'Código Sombra',
    year: 2024,
    seasons: 1,
    genre: 'Ação',
    rating: 14,
    quality: '4K',
    description: 'Uma hacker rebelde se torna alvo de uma organização secreta após descobrir seus segredos mais obscuros.',
    cast: [
      { name: 'Roberta Lins', role: 'Ghost' },
      { name: 'Ivan Costa', role: 'Cipher' },
    ],
    creator: 'Alexandre Neves',
    colorFrom: '#0a0814',
    colorTo: '#141020',
    type: 'series',
  },
  {
    id: 's5',
    title: 'Doces Acasos',
    year: 2023,
    seasons: 2,
    genre: 'Comédia',
    rating: 10,
    quality: 'HD',
    description: 'Dois desconhecidos vivem situações cada vez mais improváveis que parecem empurrá-los um para o outro.',
    cast: [
      { name: 'Renata Luz', role: 'Iris' },
      { name: 'Thiago Neves', role: 'Samy' },
    ],
    creator: 'Paula Monteiro',
    colorFrom: '#1a0818',
    colorTo: '#30102c',
    type: 'series',
  },
  {
    id: 's6',
    title: 'A Queda da Verdade',
    year: 2024,
    seasons: 1,
    genre: 'Crime',
    rating: 16,
    quality: 'HD',
    description: 'Uma promotora descobre que o caso mais famoso da cidade esconde uma rede de corrupção policial.',
    cast: [
      { name: 'Fernanda Oliva', role: 'Promotora Mel' },
      { name: 'Carlos Duarte', role: 'Delegado Rios' },
    ],
    creator: 'Raul Mendes',
    colorFrom: '#100c08',
    colorTo: '#1e1810',
    type: 'series',
  },
  {
    id: 's7',
    title: 'Guardiões de Étera',
    year: 2023,
    seasons: 3,
    genre: 'Fantasia',
    rating: 12,
    quality: 'HD',
    description: 'Em um mundo de magia e conflito, três jovens descobrem que são os últimos de uma linhagem de guardiões.',
    cast: [
      { name: 'Sofia Gomes', role: 'Lyra' },
      { name: 'Mateus Rios', role: 'Kael' },
      { name: 'Bruna Silva', role: 'Seren' },
    ],
    creator: 'Daniela Farias',
    colorFrom: '#0a1408',
    colorTo: '#142810',
    type: 'series',
  },
  {
    id: 's8',
    title: 'Rua Sem Saída',
    year: 2024,
    seasons: 1,
    genre: 'Suspense',
    rating: 16,
    quality: 'HD',
    description: 'Moradores de uma rua pacata percebem que estão sendo vigiados – e que o perigo está entre eles.',
    cast: [
      { name: 'Vitória Campos', role: 'Elena' },
      { name: 'Jorge Lima', role: 'Nelson' },
    ],
    creator: 'Flávio Assis',
    colorFrom: '#0e1014',
    colorTo: '#181c24',
    type: 'series',
  },
  {
    id: 's9',
    title: 'Do Outro Lado do Mar',
    year: 2023,
    seasons: 2,
    genre: 'Drama',
    rating: 12,
    quality: 'HD',
    description: 'Duas famílias em continentes distintos descobrem que suas histórias estão ligadas por um naufrágio de 50 anos atrás.',
    cast: [
      { name: 'Lara Mendes', role: 'Clara' },
      { name: 'Afonso Ramos', role: 'Tomás' },
    ],
    creator: 'Cecília Porto',
    colorFrom: '#081018',
    colorTo: '#101c2c',
    type: 'series',
  },
  {
    id: 's10',
    title: 'Plantão Vermelho',
    year: 2024,
    seasons: 1,
    genre: 'Drama',
    rating: 14,
    quality: 'HD',
    description: 'A vida caótica e emocionante dos médicos de um pronto-socorro numa cidade superpovoada.',
    cast: [
      { name: 'Daniela Souza', role: 'Dra. Aura' },
      { name: 'Marco Pinto', role: 'Dr. Renan' },
    ],
    creator: 'Luísa Campos',
    colorFrom: '#1a0808',
    colorTo: '#2c1010',
    type: 'series',
  },
  {
    id: 's11',
    title: 'Risos Garantidos',
    year: 2024,
    seasons: 1,
    genre: 'Comédia',
    rating: 10,
    quality: 'HD',
    description: 'Cinco colegas de trabalho tentam manter um startup vivo enquanto suas vidas pessoais desmoronam de forma hilária.',
    cast: [
      { name: 'Paulo Salgado', role: 'Neto' },
      { name: 'Amanda Torres', role: 'Lulu' },
    ],
    creator: 'Felipe Costa',
    colorFrom: '#1e1808',
    colorTo: '#382e10',
    type: 'series',
  },
  {
    id: 's12',
    title: 'No Rastro do Crime',
    year: 2023,
    seasons: 2,
    genre: 'Crime',
    rating: 16,
    quality: 'HD',
    description: 'Um detetive aposentado é chamado de volta a serviço para resolver um crime que parece impossível.',
    cast: [
      { name: 'Rui Fonseca', role: 'Detetive Nilo' },
      { name: 'Letícia Melo', role: 'Inspetora Paz' },
    ],
    creator: 'Márcio Dutra',
    colorFrom: '#100e0a',
    colorTo: '#1e1c14',
    type: 'series',
  },
  {
    id: 's13',
    title: 'Frequência Zero',
    year: 2024,
    seasons: 1,
    genre: 'Ficção científica',
    rating: 14,
    quality: '4K',
    description: 'Uma radioastrônoma capta um sinal alienígena e precisa decifrar sua mensagem antes que o governo a silencie.',
    cast: [
      { name: 'Isadora Nunes', role: 'Dra. Vera' },
      { name: 'Davi Costa', role: 'Agente Cross' },
    ],
    creator: 'Nelson Braga',
    colorFrom: '#080c1a',
    colorTo: '#10162e',
    type: 'series',
  },
  {
    id: 's14',
    title: 'Corações em Fuga',
    year: 2024,
    seasons: 1,
    genre: 'Romance',
    rating: 12,
    quality: 'HD',
    description: 'Dois fugitivos com passados misteriosos formam uma aliança inesperada e descobrem que escapar pode ser fácil – mas esquecer, não.',
    cast: [
      { name: 'Valentina Ramos', role: 'Mia' },
      { name: 'Bruno Lacerda', role: 'Leo' },
    ],
    creator: 'Priscila Gomes',
    colorFrom: '#1a0818',
    colorTo: '#2c1028',
    type: 'series',
  },
  {
    id: 's15',
    title: 'O Segredo da Floresta',
    year: 2023,
    seasons: 2,
    genre: 'Suspense',
    rating: 14,
    quality: 'HD',
    description: 'Uma pesquisadora ambiental descobre que a floresta que está estudando esconde segredos que não são naturais.',
    cast: [
      { name: 'Mara Figueiredo', role: 'Dra. Zoe' },
      { name: 'Ciro Melo', role: 'Ranger Dion' },
    ],
    creator: 'Adriana Pires',
    colorFrom: '#081408',
    colorTo: '#102010',
    type: 'series',
  },
  {
    id: 's16',
    title: 'Reinos de Cinzas',
    year: 2024,
    seasons: 1,
    genre: 'Fantasia',
    rating: 16,
    quality: '4K',
    description: 'Após uma guerra devastadora, reinos rivais precisam se unir para enfrentar uma ameaça ainda maior.',
    cast: [
      { name: 'Rodrigo Castelo', role: 'Rei Oryn' },
      { name: 'Sabrina Luz', role: 'Rainha Mira' },
    ],
    creator: 'Fábio Xavier',
    colorFrom: '#180a08',
    colorTo: '#2c100e',
    type: 'series',
  },
  {
    id: 's17',
    title: 'Liga dos Incríveis',
    year: 2024,
    seasons: 1,
    genre: 'Ação',
    rating: 10,
    quality: 'HD',
    description: 'Um grupo de jovens com habilidades especiais se une para proteger a cidade de vilões cada vez mais poderosos.',
    cast: [
      { name: 'Theo Ramos', role: 'Spark' },
      { name: 'Giovana Lima', role: 'Vento' },
      { name: 'Kauê Neves', role: 'Rocha' },
    ],
    creator: 'Tatiana Melo',
    colorFrom: '#081618',
    colorTo: '#102830',
    type: 'series',
  },
  {
    id: 's18',
    title: 'Diário de Uma Garota Comum',
    year: 2023,
    seasons: 2,
    genre: 'Comédia',
    rating: 10,
    quality: 'HD',
    description: 'Uma adolescente nada popular descobre que seu diário secreto está sendo lido pela escola inteira.',
    cast: [
      { name: 'Luna Carvalho', role: 'Bea' },
      { name: 'Noah Santos', role: 'Dani' },
    ],
    creator: 'Camila Assis',
    colorFrom: '#1a0810',
    colorTo: '#300e1c',
    type: 'series',
  },
]

export const CHANNELS: Channel[] = [
  {
    id: 'c1',
    number: 101,
    name: 'Arena Sports 1',
    category: 'Esportes',
    currentProgram: 'Liga Nacional de Vôlei',
    programs: [
      { time: '18:00', endTime: '20:00', title: 'Liga Nacional de Vôlei', isLive: true },
      { time: '20:00', endTime: '20:30', title: 'Sports Highlights' },
      { time: '20:30', endTime: '21:00', title: 'Vôlei na Prática' },
      { time: '21:00', endTime: '23:00', title: 'Copa de Basquete' },
    ],
    logoColor: '#1a3a6b',
    logoText: 'A',
  },
  {
    id: 'c2',
    number: 102,
    name: 'Arena Sports 2 HD',
    category: 'Esportes',
    currentProgram: 'Campeonato de Tênis',
    programs: [
      { time: '18:00', endTime: '20:00', title: 'Campeonato de Tênis', isLive: true },
      { time: '20:00', endTime: '22:00', title: 'Futebol Ao Vivo' },
      { time: '22:00', endTime: '22:30', title: 'Mesa de Esportes' },
    ],
    logoColor: '#1a3a6b',
    logoText: 'A2',
  },
  {
    id: 'c3',
    number: 103,
    name: 'Max Goal TV',
    category: 'Esportes',
    currentProgram: 'Futebol Internacional',
    programs: [
      { time: '17:30', endTime: '20:00', title: 'Futebol Internacional', isLive: true },
      { time: '20:00', endTime: '21:30', title: 'Análise Tática' },
    ],
    logoColor: '#0d7a2a',
    logoText: 'MG',
  },
  {
    id: 'c4',
    number: 104,
    name: 'Prime Ball',
    category: 'Esportes',
    currentProgram: 'Basquete NBB',
    programs: [
      { time: '19:00', endTime: '21:00', title: 'Basquete NBB', isLive: true },
      { time: '21:00', endTime: '21:30', title: 'Pré-jogo' },
    ],
    logoColor: '#7a4a00',
    logoText: 'PB',
  },
  {
    id: 'c5',
    number: 105,
    name: 'Action Sports',
    category: 'Esportes',
    currentProgram: 'MMA ao Vivo',
    programs: [
      { time: '20:00', endTime: '23:00', title: 'MMA ao Vivo', isLive: true },
      { time: '23:00', endTime: '23:30', title: 'Resumo do Dia' },
    ],
    logoColor: '#6b1a1a',
    logoText: 'AS',
  },
  {
    id: 'c6',
    number: 106,
    name: 'Elite Match',
    category: 'Esportes',
    currentProgram: 'Polo Aquático',
    programs: [
      { time: '18:30', endTime: '20:30', title: 'Polo Aquático', isLive: true },
      { time: '20:30', endTime: '22:00', title: 'Natação Masters' },
    ],
    logoColor: '#1a1a6b',
    logoText: 'EM',
  },
  {
    id: 'c7',
    number: 107,
    name: 'Stadium Live',
    category: 'Esportes',
    currentProgram: 'Rugby Nacional',
    programs: [
      { time: '19:30', endTime: '21:30', title: 'Rugby Nacional', isLive: true },
      { time: '21:30', endTime: '22:00', title: 'Flash Esportivo' },
    ],
    logoColor: '#2a1a6b',
    logoText: 'ST',
  },
  {
    id: 'c8',
    number: 108,
    name: 'Sport Plus',
    category: 'Esportes',
    currentProgram: 'Atletismo Mundial',
    programs: [
      { time: '17:00', endTime: '20:00', title: 'Atletismo Mundial', isLive: true },
      { time: '20:00', endTime: '21:00', title: 'Top 10 da Semana' },
    ],
    logoColor: '#006b2a',
    logoText: 'SP+',
  },
  {
    id: 'c9', number: 201, name: 'CineMax Prime', category: 'Filmes', currentProgram: 'A Última Fronteira',
    programs: [
      { time: '18:00', endTime: '20:10', title: 'A Última Fronteira', isLive: true },
      { time: '20:10', endTime: '22:30', title: 'Noite de Ação' },
      { time: '22:30', endTime: '00:40', title: 'Clássico da Madrugada' },
    ],
    logoColor: '#102a52', logoText: 'CX',
  },
  {
    id: 'c10', number: 202, name: 'Tela Premium', category: 'Filmes', currentProgram: 'Cidade dos Sonhos',
    programs: [
      { time: '17:40', endTime: '19:50', title: 'Cidade dos Sonhos', isLive: true },
      { time: '19:50', endTime: '22:00', title: 'Sessão Blockbuster' },
    ],
    logoColor: '#3a1052', logoText: 'TP',
  },
  {
    id: 'c11', number: 203, name: 'Film & Co', category: 'Filmes', currentProgram: 'O Enigma Final',
    programs: [
      { time: '18:30', endTime: '20:40', title: 'O Enigma Final', isLive: true },
      { time: '20:40', endTime: '22:50', title: 'Suspense da Noite' },
    ],
    logoColor: '#52102a', logoText: 'FC',
  },
  {
    id: 'c12', number: 301, name: 'Séries Mania', category: 'Séries', currentProgram: 'Corações de Aurora',
    programs: [
      { time: '18:00', endTime: '19:00', title: 'Corações de Aurora', isLive: true },
      { time: '19:00', endTime: '20:00', title: 'Chamas do Destino' },
      { time: '20:00', endTime: '21:00', title: 'Maratona Drama' },
    ],
    logoColor: '#0d4d4d', logoText: 'SM',
  },
  {
    id: 'c13', number: 302, name: 'Drama Plus', category: 'Séries', currentProgram: 'A Cidade Submersa',
    programs: [
      { time: '18:20', endTime: '19:20', title: 'A Cidade Submersa', isLive: true },
      { time: '19:20', endTime: '20:20', title: 'O Guardião da Neblina' },
    ],
    logoColor: '#4d2a0d', logoText: 'D+',
  },
  {
    id: 'c14', number: 401, name: 'News 24h', category: 'Notícias', currentProgram: 'Jornal das Seis',
    programs: [
      { time: '18:00', endTime: '19:00', title: 'Jornal das Seis', isLive: true },
      { time: '19:00', endTime: '20:00', title: 'Economia Hoje' },
      { time: '20:00', endTime: '21:00', title: 'Mundo Agora' },
    ],
    logoColor: '#0a2a5a', logoText: 'N24',
  },
  {
    id: 'c15', number: 402, name: 'Global News', category: 'Notícias', currentProgram: 'Cobertura Internacional',
    programs: [
      { time: '18:00', endTime: '19:30', title: 'Cobertura Internacional', isLive: true },
      { time: '19:30', endTime: '21:00', title: 'Debate da Noite' },
    ],
    logoColor: '#5a0a0a', logoText: 'GN',
  },
  {
    id: 'c16', number: 501, name: 'Discovery Wild', category: 'Documentários', currentProgram: 'Planeta Selvagem',
    programs: [
      { time: '18:00', endTime: '19:00', title: 'Planeta Selvagem', isLive: true },
      { time: '19:00', endTime: '20:00', title: 'Oceanos Profundos' },
    ],
    logoColor: '#1a4d0d', logoText: 'DW',
  },
  {
    id: 'c17', number: 502, name: 'História Viva', category: 'Documentários', currentProgram: 'Civilizações Perdidas',
    programs: [
      { time: '18:30', endTime: '19:30', title: 'Civilizações Perdidas', isLive: true },
      { time: '19:30', endTime: '20:30', title: 'Grandes Guerras' },
    ],
    logoColor: '#4d3a0d', logoText: 'HV',
  },
  {
    id: 'c18', number: 601, name: 'Kids Fun', category: 'Desenhos', currentProgram: 'Os Exploradores',
    programs: [
      { time: '18:00', endTime: '18:30', title: 'Os Exploradores', isLive: true },
      { time: '18:30', endTime: '19:00', title: 'Turma da Floresta' },
      { time: '19:00', endTime: '19:30', title: 'Robôs Amigos' },
    ],
    logoColor: '#0d6b52', logoText: 'KF',
  },
  {
    id: 'c19', number: 602, name: 'Cartoon Mix', category: 'Desenhos', currentProgram: 'Aventuras Mágicas',
    programs: [
      { time: '18:00', endTime: '18:30', title: 'Aventuras Mágicas', isLive: true },
      { time: '18:30', endTime: '19:00', title: 'Super Heróis Jr.' },
    ],
    logoColor: '#6b0d52', logoText: 'CM',
  },
]

export const WATCHING_ITEMS: WatchingItem[] = [
  {
    id: 'w1',
    title: 'O Guardião da Neblina',
    episode: 'S1 • E4',
    progress: 35,
    colorFrom: '#0a1020',
    colorTo: '#142038',
    isNew: true,
  },
  {
    id: 'w2',
    title: 'Corações de Aurora',
    episode: 'S1 • E6',
    progress: 62,
    colorFrom: '#1a0a20',
    colorTo: '#2c1038',
  },
  {
    id: 'w3',
    title: 'Chamas do Destino',
    episode: 'S2 • E3',
    progress: 18,
    colorFrom: '#200808',
    colorTo: '#381010',
  },
  {
    id: 'w4',
    title: 'A Cidade Submersa',
    episode: 'S1 • E2',
    progress: 80,
    colorFrom: '#080e1a',
    colorTo: '#101c30',
  },
]

export const KIDS_ITEMS: KidsItem[] = [
  { id: 'k1', title: 'Aventuras no Céu', colorFrom: '#38bdf8', colorTo: '#2563eb' },
  { id: 'k2', title: 'O Dragão e o Menino', colorFrom: '#fb923c', colorTo: '#f97316' },
  { id: 'k3', title: 'Amiguinhos do Planeta', colorFrom: '#34d399', colorTo: '#059669' },
  { id: 'k4', title: 'Exploradores da Floresta', colorFrom: '#a3e635', colorTo: '#16a34a' },
  { id: 'k5', title: 'Robôs Saltitantes', colorFrom: '#c084fc', colorTo: '#7c3aed' },
  { id: 'k6', title: 'A Princesa Estrela', colorFrom: '#f472b6', colorTo: '#db2777' },
  ]

/** Whether a plan label represents a free trial / test (vs a paid plan). */
export function isTrialPlan(plan: string): boolean {
  return /teste|trial|gr[áa]tis|demo/i.test(plan)
}

/** Format a trial countdown as "1 hora e 15 restantes" or "30 minutos restantes". */
export function formatTrialRemaining(ms: number): string {
  if (ms <= 0) return 'Teste expirado'
  const totalMin = Math.floor(ms / 60000)
  const h = Math.floor(totalMin / 60)
  const min = totalMin % 60
  if (h > 0) return `${h} ${h === 1 ? 'hora' : 'horas'} e ${min} restantes`
  return `${min} ${min === 1 ? 'minuto' : 'minutos'} restantes`
}

/** Days left until a DD/MM/YYYY validity date (never negative). */
export function daysRemaining(validity: string): number {
  const [d, m, y] = validity.split('/').map(Number)
  if (!d || !m || !y) return 0
  const end = new Date(y, m - 1, d)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const diff = Math.ceil((end.getTime() - today.getTime()) / 86_400_000)
  return Math.max(diff, 0)
}

export const USER: User = {
  name: 'João da Silva',
  email: 'joao.silva@email.com',
  plan: 'Plano mensal',
  validity: '10/07/2026',
  deviceCode: '3GK689',
  notifications: true,
  autoplay: true,
  parentalControl: '12 anos',
  language: 'Português (Brasil)',
  videoQuality: 'Automático',
  connectedDevices: 3,
  appVersion: '1.1.5',
}

export const MOVIE_CATEGORIES = [
  'Lançamentos',
  'Em alta',
  'Ação',
  'Comédia',
  'Drama',
  'Suspense',
  'Ficção científica',
  'Terror',
  'Infantil',
]

export const SERIES_CATEGORIES = [
  'Lançamentos',
  'Em alta',
  'Drama',
  'Suspense',
  'Ação',
  'Comédia',
  'Crime',
  'Ficção científica',
  'Romance',
  'Infantil',
]

export const CHANNEL_CATEGORIES = [
  'Todos',
  'Esportes',
  'Filmes',
  'Séries',
  'Notícias',
  'Documentários',
  'Desenhos',
]

// Inject pre-computed gradient strings so components never run template literals on each render
MOVIES.forEach((m) => { m.gradient = g(m.colorFrom, m.colorTo) })
SERIES.forEach((s) => { s.gradient = g(s.colorFrom, s.colorTo) })
